import { defineStore } from 'pinia'
import { ref } from 'vue'

export const useGroupStore = defineStore('group', () => {
  const groups = ref([
    {
      id: 1,
      groupName: 'Savings Circle',
      activity: 'Monthly Contributions',
      contributionAmount: 10000,
      members: 12,
      bgImage: '/src/assets/images/user.png',
      isAdmin: true,
    },
    {
      id: 2,
      groupName: 'Travel Fund',
      activity: 'Weekly Savings',
      contributionAmount: 5000,
      members: 8,
      bgImage: '/src/assets/images/user.png',
      isAdmin: true,
    },
    {
      id: 3,
      groupName: 'Business Members',
      activity: 'Quarterly Investment',
      contributionAmount: 50000,
      members: 5,
      bgImage: '/src/assets/images/user.png',
      isAdmin: false,
    },
    {
      id: 4,
      groupName: 'Business Partners',
      activity: 'Quarterly Investment',
      contributionAmount: 50000,
      members: 5,
      bgImage: '/src/assets/images/user.png',
      isAdmin: true,
    },
    {
      id: 5,
      groupName: 'Wedding Savings',
      activity: 'Bi-Weekly Contributions',
      contributionAmount: 20000,
      members: 15,
      bgImage: '/src/assets/images/user.png',
      isAdmin: false,
    },
    {
      id: 6,
      groupName: 'Medical Fund',
      activity: 'Emergency Pool',
      contributionAmount: 15000,
      members: 10,
      bgImage: '/src/assets/images/user.png',
      isAdmin: true,
    },
    {
      id: 7,
      groupName: 'Tech Startups',
      activity: 'Monthly Investment',
      contributionAmount: 75000,
      members: 7,
      bgImage: '/src/assets/images/user.png',
      isAdmin: true,
    },
    {
      id: 8,
      groupName: 'Church Group',
      activity: 'Tithe & Welfare Contributions',
      contributionAmount: 5000,
      members: 25,
      bgImage: '/src/assets/images/user.png',
      isAdmin: false,
    },
    {
      id: 9,
      groupName: 'Football Fans Club',
      activity: 'Weekly Entertainment Fund',
      contributionAmount: 3000,
      members: 20,
      bgImage: '/src/assets/images/user.png',
      isAdmin: true,
    },
    {
      id: 10,
      groupName: 'Book Club',
      activity: 'Monthly Reading Fund',
      contributionAmount: 2500,
      members: 18,
      bgImage: '/src/assets/images/user.png',
      isAdmin: false,
    },
    {
      id: 11,
      groupName: 'Community Builders',
      activity: 'Quarterly Projects',
      contributionAmount: 40000,
      members: 30,
      bgImage: '/src/assets/images/user.png',
      isAdmin: true,
    },
    {
      id: 12,
      groupName: 'Family Support',
      activity: 'Monthly Family Pool',
      contributionAmount: 12000,
      members: 9,
      bgImage: '/src/assets/images/user.png',
      isAdmin: false,
    },
  ])

  return { groups }
})
